# this yaml file can also be created by doing
# see other templates at : https://github.com/kubernetes/website/blob/main/content/en/examples/pods/simple-pod.yaml
# Other templates at:
#  https://github.com/kubernetes/website/tree/main/content/en/examples/pods
#  https://github.com/kubernetes/examples/blob/master/guestbook/all-in-one/guestbook-all-in-one.yaml
# kubectl run nginx-container --image=nginx --dry-run=client -o yaml

# https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#resources
apiVersion: v1

# https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#types-kinds
kind: Pod

# https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#metadata
metadata:
  name: nginx
  labels:
    app: nginx
    type: loadbalancer
    
# https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#spec-and-status
spec:
  containers:
  - name: nginx-container
    image: nginx
